server.port: 8080

## ===============================
## = Hibernate datasource
## ===============================
spring.datasource:
  url: jdbc:h2:file:./omsdemo_db;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
  username: sa
  driver-class-name: org.h2.Driver
  initialization-mode: ALWAYS
  sql-script-encoding: utf-8

## ===============================
## = JPA configurations
## ===============================
spring.jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  show-sql: false
  hibernate.ddl-auto: 'create'